name: Continuous Beaning

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3.0.2
        - uses: actions/setup-go@v4
          with:
            go-version: '1.20.0'
        - run: test -z $(go fmt ./...)
